# Generated by Django 5.2.4 on 2025-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_providerprofile_google_token_expiry_analyticsapi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerprofile",
            name="calendarID",
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="google_calendar_connected",
            field=models.BooleanField(default=False),
        ),
    ]
