# Generated by Django 5.2.4 on 2025-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_providerprofile_calendarid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="event_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
