# Generated by Django 5.2.4 on 2025-07-11 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_providerprofile_end_time_providerprofile_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="date",
            new_name="date_end",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
