# Generated by Django 5.2.4 on 2025-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_date_appointment_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="rate",
            field=models.FloatField(default=0),
        ),
    ]
