# Generated by Django 5.2.4 on 2025-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="special_requests",
            field=models.TextField(default="None"),
        ),
    ]
