# Generated by Django 5.2.4 on 2025-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_appointment_special_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="recurrence_frequency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="recurrence_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
