# Generated by Django 5.2.4 on 2025-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
