# Generated by Django 5.2.4 on 2025-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_appointment_bad_cancel_appointment_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerprofile",
            name="service_name",
            field=models.CharField(max_length=50),
        ),
    ]
